[package]
name = "iceth"
version = "0.1.0"
description = "Ethereum on IC."
authors = ["John Plevyak <jplevyak@gmail.com>"]
readme = "README.md"
edition = "2021"

[dependencies]
candid = "0.8"
ic-canister-log = "0.1.0"
ic-canister-serve = "0.1.0"
ic-certified-map = "0.3"
ic-cdk = "0.7"
ic-cdk-macros = "0.6"
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5"
json5 = "0.4"
num = "0.4"
num-traits = "0.2"
num-derive = "0.3"
serde = "1"
serde_bytes = "0.11"
serde_cbor = "0.11"
sha2 = "^0.10"
url = "2.4"

[profile.release]
debug = false
lto = true
opt-level = 'z'
